# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98fb0d49295ba0ea2464ed968cad72b5b1cfed56e52dd4bd491b03624e27472b20af5f25ae691802c5d96417ec36dccb4528c5fb1a6596c52ef5c8e91378e3c1

test:
  secret_key_base: 5e3f9b1575d67a436a0e88c194692585fbdb98578432246548ff3b63caa92e67118f6a8582dd5f78a20b56b6fd7017d7c089ab7042fbb59c8cab46a675252552

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
